### ISSUE TITLE
new topic and reply background fully transparent = unusable

### ISSUE THREAD

**Issue by drewauff** [luetage/vivaldi_forum_mod#27]
cannot write new topic as background is completely transparent .

same goes for reply box..

unusable for anything other than browsing..needs to be fixed.

All dark themes have this.

Im on Vivaldi 3.7

bloody Dark Reader..nvm

**Comment by luetage** [comment]
Yeah, the extension doesn’t go well with darkreader, but you can just whitelist Vivaldi Forum. Did we talk about this on the forums too? I’m just catching up on some stuff and can’t really remember :/

**Comment by drewauff** [comment]
I believe we did, we got it sorted. Also some sites actively block darkreader.
